namespace BerremanTests

open Berreman.Constants                                // the nm / mkm / mm units of measure
open Berreman.MathNetNumericsMath                      // ComplexMatrix — the read seam into the engine's tensors
open Berreman.Geometry
open Berreman.Fields
open Berreman.MaterialProperties
open Berreman.Media
open Berreman.Solvers
open OpticalProperties.Active
open OpticalConstructor.Domain
open OpticalConstructor.Domain.MuellerReconstruction   // Retardance — reused, not re-declared
open OpticalConstructor.Domain.MuellerInverse
open OpticalConstructor.Optimization
open Xunit
open BerremanTests.MatrixComparison

/// Spec 0044 — the inverse problem for a transparent, optically active, anisotropic, homogeneous
/// material. Quartz at a single wavelength is used as ground truth: the forward "measured" data is
/// generated by this repository's own Berreman solver, then the material constants are recovered from it
/// and the round trip is asserted. Because the truth is known exactly, these facts measure the INVERSE
/// MACHINERY, not the physics.
///
/// Every fact here is self-contained. The data is generated in-test from the library, so there is no
/// external data, no committed fixture, no skip path, and no file of any kind is read.
///
/// Deliberately NOT asserted here — each is a candidate for a future slice:
///   - noise robustness (σ ≈ 1e-3 on the normalized elements), at which point confidence-interval
///     coverage becomes the right assertion and `g₁₁` should degrade markedly relative to `g₃₃`,
///     mirroring the ±10 % the literature reports for `g₁₁`;
///   - multistart / global search, needed once the retardance order is unknown;
///   - the rotating-analyzer intensity-level variant, which would reuse spec 0042's `kron4` design-matrix
///     machinery end to end instead of consuming Mueller matrices directly;
///   - Lu-Chipman polar decomposition of the recovered matrices;
///   - dispersion (this spec fixes one wavelength), biaxial or absorbing materials;
///   - fitting thickness and crystal orientation as nuisance parameters (both are known here, spec R2).
type MuellerInverseTests() =

    /// Radians per degree, reached by its full module path (mirrors `MuellerReconstructionTests`). Bound
    /// here, ahead of the members (FS0960: in a class type every `let` binding precedes the first member).
    let degree = Berreman.MathNetNumericsMath.degree

    /// The same element-by-element Mueller compare loop `MuellerMatrixTests` and
    /// `MuellerReconstructionTests` use, over the shared `allowedDiff` tolerance — no hand-rolled epsilon.
    let assertMuellerEqual (expected : MuellerMatrix) (actual : MuellerMatrix) =
        for i in 0 .. 3 do
            for j in 0 .. 3 do
                let e = Propagation.muellerElement expected i j
                let a = Propagation.muellerElement actual i j
                Assert.True(abs (e - a) < allowedDiff, $"M[{i},{j}]: expected {e}, got {a}")

    // =================================================================================================
    // Ground truth: quartz at 632.8 nm.
    //
    // Spec R3 puts the material in the TEST rather than in the OpticalProperties library. The library has
    // no quartz: the gyration constants exist only as a fixture in RhoWithDispValueTests and as a doc
    // comment in MaterialComplexityEditor, and there is no quartz permittivity anywhere. Rather than add a
    // shipped material for a single test, the constants live here with their provenance.
    //
    // Two things a reader must know about these numbers, so that nobody mistakes a synthetic round trip
    // for a literature validation:
    //
    //   * g33 agrees with the literature almost exactly (10.1 here vs Arteaga/Canillas/Jellison's
    //     10.06 ± 0.07 e-5 at 632.8 nm), but g11 sits at the HIGH end (5.9 vs 4.8 ± 0.5 e-5; ratio -0.584
    //     vs -0.486). Since the forward data is generated FROM these values, they are the ground truth by
    //     definition and the discrepancy cannot affect pass or fail.
    //
    //   * Handedness is one overall sign. Active.assembleRho applies hand.sign to every component, so the
    //     left-handed enantiomorph is the negation of this set. These are the right-handed values.
    // =================================================================================================

    /// He-Ne. The wavelength the quartz literature is densest at, and the one every constant below is
    /// quoted for.
    let waveLength = WaveLength.nm 632.8<nm>

    /// Ghosh 1999 ordinary Sellmeier for alpha-quartz, evaluated at 0.6328 um.
    let quartzOrdinaryIndex = RefractionIndex 1.542606

    /// Ghosh 1999 extraordinary Sellmeier for alpha-quartz, evaluated at 0.6328 um. The birefringence is
    /// therefore n_e - n_o = 0.009045.
    let quartzExtraordinaryIndex = RefractionIndex 1.551651

    /// Gyration component perpendicular to the optic axis (class 32, 24 C). Same value as the existing
    /// RhoWithDispValueTests fixture.
    let quartzG11 = RhoValue 5.9e-5

    /// Gyration component along the optic axis. Same value as the existing RhoWithDispValueTests fixture.
    let quartzG33 = RhoValue -10.1e-5

    /// The ground-truth parameter set the forward data is generated from and the fit must recover.
    let quartz : MaterialParameters =
        {
            ordinaryIndex = quartzOrdinaryIndex
            extraordinaryIndex = quartzExtraordinaryIndex
            g11 = quartzG11
            g33 = quartzG33
        }

    /// Build the engine's optical properties for a uniaxial gyrotropic (class 3/32/4/422/6/622) crystal
    /// from the four unknowns. This is the ONE material-specific function in the whole pipeline, and the
    /// reason MuellerInverse takes it as a parameter rather than knowing it: the Domain project does not
    /// reference OpticalProperties, and the inverse machinery is not specific to quartz.
    ///
    /// It delegates entirely to the existing Active.OpticalProperties.type_3_4_6_Crystal builder, so the
    /// diagonal forms diag(n_o^2, n_o^2, n_e^2) and diag(g11, g11, g33) are the engine's own and are not
    /// re-derived here.
    let buildUniaxialGyrotropic (p : MaterialParameters) : OpticalProperties =
        OpticalProperties.type_3_4_6_Crystal
            (EpsValue.fromRefractionIndex p.ordinaryIndex)
            (EpsValue.fromRefractionIndex p.extraordinaryIndex)
            p.g11
            p.g33

    /// Spec R4: three internal reflections, stated explicitly at the composition root rather than
    /// inherited from SolverParameters.defaultValue.
    ///
    /// This is a physics choice, not a knob. With numberOfReflections = 3 the Plate branch of the solver
    /// accumulates five emerging beams and getMuellerMatrix SUMS their Mueller matrices, so
    /// muellerMatrixT() is the direct beam plus the beam that has bounced twice inside the plate. A sum of
    /// Mueller-Jones matrices is in general weakly DEPOLARIZING - which is why the realizability fact
    /// below asserts a bounded depolarization index rather than strict non-depolarization, and why the
    /// closed-form analytic inversion is used for starting values rather than as the reported answer.
    /// At quartz's ~4.55 % surface reflectance the second transmitted beam carries only ~0.2 % of the
    /// first, so the effect is small but real.
    let solverParameters : SolverParameters = { numberOfReflections = 3 }

    /// The real Berreman-backed forward model, wired once for the whole class.
    let forward = createBerremanForward buildUniaxialGyrotropic solverParameters

    // =================================================================================================
    // The measurement set (spec §3.4, C1-C4).
    //
    // Why more than one configuration is needed at all. A wave only ever sees the components of the
    // material tensors TRANSVERSE to its own propagation direction, so no single propagation direction can
    // constrain the whole tensor:
    //
    //   z-cut, normal incidence (C1): the wave travels along the optic axis. The two transverse directions
    //           are equivalent, so there is NO linear birefringence at all and the plate is a pure
    //           circular retarder. The transverse Rho components are both g11, so this configuration
    //           measures g11 cleanly and is completely BLIND to g33 (asserted by the ablation fact below).
    //
    //   x-cut, normal incidence (C3): the wave travels across the optic axis. Now one transverse direction
    //           is ordinary and the other extraordinary, so linear birefringence is maximal and buries the
    //           much smaller optical activity - and the transverse Rho components are g11 and g33, so this
    //           is the configuration that makes g33 reachable at all. It is the hard measurement, exactly
    //           as the analogous case is in the literature.
    //
    // The trap: those two regimes CANNOT be reached from one sample by tilting it. Snell's law caps the
    // internal angle at arcsin(1/n_o) = 40.41 deg for quartz, so a z-cut plate never gets the wave more
    // than 40 deg off its optic axis however far it is tilted. That is why C3/C4 exist, and it is the same
    // constraint that makes the transverse gyration component the poorly-determined one in published
    // measurements (Arteaga/Canillas/Jellison report their axial component to 0.7 % and their transverse
    // one only to ~10 % from a single z-cut crystal). The ablation fact below asserts the resulting
    // unobservability directly rather than assuming it.
    //
    // Thickness is KNOWN (spec R2) and is not fitted; it is still a DESIGN variable, because it controls
    // the shape of the chi-squared surface:
    //
    //   * C1 is 1.0 mm. It carries NO linear retardance (normal incidence on a z-cut), so thickness costs
    //     nothing here and buys a large, well-conditioned optical rotation of 18.62 deg.
    //   * Every configuration that DOES carry linear retardance is 20 um, which is 0.286 wave at 632.8 nm.
    //     Sub-wave retardance keeps the residual smooth and unimodal in n_e - n_o; at 1 mm the same
    //     configuration would be 14.29 waves and the residual would oscillate into a dense forest of local
    //     minima roughly half a fringe apart.
    //
    // NOTE, and a correction to spec §3.4 as written: the spec put C2 (z-cut, OBLIQUE incidence) at
    // 1.0 mm, on the reasoning that a z-cut plate carries no linear retardance. That reasoning holds only
    // at normal incidence. Tilted, the internal angle is non-zero, the effective birefringence grows as
    // sin^2 t, and a 1 mm z-cut plate at 70 deg incidence carries ~5.9 waves - exactly the multimodality
    // §3.3 exists to avoid. C2 therefore uses the same 20 um plate, which puts it at ~0.12 wave. This
    // applies the spec's own stated rule to a configuration the spec mis-classified.
    // =================================================================================================

    /// A 1.0 mm plate — used only where there is no linear retardance to alias.
    let thickPlate = Thickness.mm 1.0<mm>

    /// A 20 um plate — sub-wave linear retardance, used by every retardance-bearing configuration.
    let thinPlate = Thickness.mkm 20.0<mkm>

    let configuration (cut : OpticAxisCut) (thickness : Thickness) (incidenceDeg : double) (azimuthDeg : double) (observable : Observable) : MeasurementConfiguration =
        {
            cut = cut
            thickness = thickness
            incidenceAngle = Angle.degree incidenceDeg |> IncidenceAngle.create
            azimuth = SampleAzimuth.degree azimuthDeg
            observable = observable
            waveLength = waveLength
        }

    /// C1 — z-cut, normal incidence, 1.0 mm. The anchor: a pure optical rotator, and the configuration
    /// that fixes g11 almost independently of everything else — while being completely blind to g33.
    let c1 : MeasurementConfiguration list =
        [ configuration ZCut thickPlate 0.0 0.0 TransmittedMueller ]

    /// C2 — z-cut, oblique incidence sweep, both azimuths, transmission and reflection. Supplies the
    /// Fresnel/angle information that pins the absolute indices, and lets g33 begin to enter as the
    /// internal angle tilts the crystal 3-axis into the transverse plane — weakly, since Snell caps that
    /// tilt at 40.4 deg.
    let c2 : MeasurementConfiguration list =
        [ for incidence in [ 10.0; 30.0; 50.0; 70.0 ] do
            for azimuth in [ 0.0; 45.0 ] do
                for observable in [ TransmittedMueller; ReflectedMueller ] ->
                    configuration ZCut thinPlate incidence azimuth observable ]

    /// C3 — x-cut, normal incidence, four azimuths. The configuration that makes g33 identifiable at all:
    /// the optic axis lies in the surface plane, so the crystal 3-axis is transverse to the propagation
    /// direction and its Rho component finally enters.
    let c3 : MeasurementConfiguration list =
        [ for azimuth in [ 0.0; 22.5; 45.0; 67.5 ] ->
            configuration XCut thinPlate 0.0 azimuth TransmittedMueller ]

    /// C4 — x-cut, oblique sweep, both azimuths, transmission and reflection. A second independent look at
    /// g33 and extra index/angle leverage.
    let c4 : MeasurementConfiguration list =
        [ for incidence in [ 15.0; 45.0 ] do
            for azimuth in [ 0.0; 45.0 ] do
                for observable in [ TransmittedMueller; ReflectedMueller ] ->
                    configuration XCut thinPlate incidence azimuth observable ]

    let fullConfigurations = c1 @ c2 @ c3 @ c4

    /// Generate the synthetic "measured" data for a configuration set from the ground-truth parameters,
    /// failing the test on any forward-model error.
    let observe (configurations : MeasurementConfiguration list) : MuellerObservation list =
        configurations
        |> List.map (fun c ->
            match forward.muellerOf c quartz with
            | Ok m -> { configuration = c; measured = m }
            | Error e -> failwith $"the forward model failed to generate ground-truth data: %A{e}")

    // =================================================================================================
    // T7 / T8 / T9 — Stage B: the nonlinear fit, its identifiability diagnostics, and the ablation.
    // =================================================================================================

    /// The dimensionless fit space (spec §3.5). `centre` is the START GUESS, so the initial scaled vector
    /// is exactly zero; `scale` sets what one unit of each coordinate means physically.
    ///
    /// The scale choice is the whole reason this type exists. ALGLIB's Levenberg-Marquardt differentiates
    /// with a FIXED ABSOLUTE step of 1e-6, so a unit of 1e-3 in refractive index makes that step a 1e-9
    /// perturbation of n, and a unit of 1e-5 in gyration makes it a 1e-11 perturbation of g. Both are
    /// small enough to be genuinely linear and large enough to move the Mueller elements far above the
    /// solver's own numerical noise. Handing the optimizer raw physical parameters instead would make the
    /// same 1e-6 step a 1 % perturbation of g and a 6e-7 relative perturbation of n - four orders of
    /// magnitude apart, and the former far outside the linear regime a Jacobian assumes.
    let scalingAround (centre : MaterialParameters) : ParameterScaling =
        {
            centre = centre
            scale =
                {
                    ordinaryIndex = RefractionIndex 1.0e-3
                    extraordinaryIndex = RefractionIndex 1.0e-3
                    g11 = RhoValue 1.0e-5
                    g33 = RhoValue 1.0e-5
                }
        }

    /// The residual closure the optimizer drives: scaled vector -> normalized Mueller element differences.
    ///
    /// It must be TOTAL and of fixed length, because an optimizer explores freely and will hand it
    /// parameter values the forward model cannot solve. A forward failure therefore returns a large finite
    /// penalty of the correct length rather than throwing or returning a short vector: the first would
    /// abort the fit, and the second would silently change the problem being minimized.
    let residualFor (observations : MuellerObservation list) (scaling : ParameterScaling) : float[] -> float[] =
        let width = 15 * List.length observations
        fun (v : float[]) ->
            match forwardModels forward (ofScaled scaling v) observations with
            | Error _ -> Array.create width 1.0e3
            | Ok models ->
                match residualVector observations models with
                | Ok r -> r
                | Error _ -> Array.create width 1.0e3

    /// The start guess shared by the fit facts: the two gyration components 30 % wrong, the two refractive
    /// indices off by +0.2 % and +0.1 %.
    ///
    /// The perturbation is large where it can be and honest about where it cannot. 30 % on the gyration
    /// components is far outside any experimental uncertainty. The index perturbations look small in
    /// relative terms but move the BIREFRINGENCE n_e - n_o by -17 %, and birefringence, not absolute
    /// index, is what the retardance depends on. Absolute index cannot be perturbed harder for a
    /// structural reason rather than a weakness of the fit: linear retardance enters the model through cos
    /// and sin of 2 pi (n_e - n_o) d / lambda, so a start guess more than about half a fringe away lands
    /// in a different basin of attraction. That is a property of the physics, and it is exactly why the
    /// retardance-bearing samples are 20 um (0.286 wave) rather than 1 mm (14.3 waves).
    let perturbedStart : MaterialParameters =
        {
            ordinaryIndex = RefractionIndex (quartzOrdinaryIndex.value * 1.002)
            extraordinaryIndex = RefractionIndex (quartzExtraordinaryIndex.value * 1.001)
            g11 = RhoValue (quartzG11.value * 1.3)
            g33 = RhoValue (quartzG33.value * 1.3)
        }

    /// Run the fit for a configuration set from a given start guess.
    let runFit (configurations : MeasurementConfiguration list) (start : MaterialParameters) =
        let observations = observe configurations
        let scaling = scalingAround start
        let residual = residualFor observations scaling
        let solver = MuellerInverseSolver.createAlglibLevenbergMarquardt ()
        let request =
            {
                residual = residual
                initial = Array.zeroCreate 4
                // Generous box bounds in SCALED units: +-50 is +-0.05 in refractive index and +-5e-4 in
                // gyration, which brackets any physically sensible excursion while keeping the search out
                // of the degenerate region around n = 0.
                lowerBounds = Array.create 4 -50.0
                upperBounds = Array.create 4 50.0
                maxIterations = 400
                epsX = 1.0e-12
            }
        match solver.solveNonlinearLeastSquares request with
        | Ok solution -> observations, scaling, residual, solution
        | Error e -> failwith $"the inverse fit failed: %A{e}"

    let parameterNames = [| "n_o"; "n_e"; "g11"; "g33" |]

    let relativeError (actual : float) (expected : float) = abs (actual - expected) / abs expected

    // =================================================================================================
    // T1 / T2 — the forward-side pure helpers.
    // =================================================================================================

    [<Fact>]
    member _.``gyrationProjection collapses to g33 along the optic axis and to g11 across it`` () =
        // The CRYSTALLOGRAPHIC gyration projection, pinned at its two extremes. This is the literature
        // convention - the double contraction of the gyration tensor with the propagation direction - and
        // it is the bridge for comparing recovered constants against published values.
        //
        // It is NOT the convention this engine's forward model uses. The engine's Rho is the
        // bi-anisotropic tensor of D = eps E + rho H, in which propagation along z is governed by the
        // TRANSVERSE component g11 rather than by g33, so the two conventions assign the roles of the two
        // components OPPOSITELY. The forward-model fact below measures the engine's own law exactly and
        // documents the gap; nothing in this suite uses this function to predict the engine.
        let atAxis = gyrationProjection Angle.zero quartzG11 quartzG33
        let acrossAxis = gyrationProjection (Angle.degree 90.0) quartzG11 quartzG33
        Assert.True(abs (atAxis.value - quartzG33.value) < allowedDiff, $"G(0) = {atAxis.value}")
        Assert.True(abs (acrossAxis.value - quartzG11.value) < allowedDiff, $"G(90) = {acrossAxis.value}")

        // At 45 deg the two contribute equally — the only angle at which a single measurement constrains
        // their SUM but neither individually.
        let atHalf = gyrationProjection (Angle.degree 45.0) quartzG11 quartzG33
        let expectedHalf = 0.5 * (quartzG11.value + quartzG33.value)
        Assert.True(abs (atHalf.value - expectedHalf) < allowedDiff, $"G(45) = {atHalf.value}")

    [<Fact>]
    member _.``internalAngle is capped by the critical angle, so a z-cut plate cannot reach the g11 regime`` () =
        // Snell's law, and the constraint that forces a second sample cut into the experiment design.
        // However far a z-cut plate is tilted, the internal angle saturates at arcsin(1/n_o) = 40.41 deg,
        // where sin^2 t = 0.42 — so g11 can never carry more than 42 % of the projection weight from a
        // z-cut sample. This fact is the quantitative justification for C3 and C4 existing.
        let grazing = internalAngle quartzOrdinaryIndex (Angle.degree 89.0 |> IncidenceAngle.create)
        let expectedCap = asin (1.0 / quartzOrdinaryIndex.value) / degree
        Assert.True(grazing.degrees < expectedCap + 1.0e-9, $"internal angle at grazing = {grazing.degrees}")
        Assert.True(grazing.degrees > expectedCap - 0.1, $"internal angle at grazing = {grazing.degrees}, cap = {expectedCap}")

        let weight = sin grazing.value ** 2.0
        Assert.True(weight < 0.43, $"g11 projection weight at grazing incidence = {weight}")

        // Normal incidence goes straight through: no refraction, no projection weight on g11 at all.
        let normal = internalAngle quartzOrdinaryIndex IncidenceAngle.normal
        Assert.True(abs normal.value < allowedDiff, $"internal angle at normal incidence = {normal.degrees}")

    [<Fact>]
    member _.``orientForCut carries the optic axis from the surface normal into the surface plane`` () =
        // The crystal is built in its own frame, with the optic axis on the 3-axis: that is what makes
        // eps_33 = n_e^2 and rho_33 = g33. A z-cut sample needs no rotation; an x-cut sample must have
        // that axis carried into the surface plane.
        //
        // The expected tensors are read element-wise from the ENGINE's own types rather than rebuilt, so
        // this fact checks the orientation, not the tensor construction (which Active.fs already owns).
        let props = buildUniaxialGyrotropic quartz
        let nOrdSq = quartzOrdinaryIndex.value ** 2.0
        let nExtSq = quartzExtraordinaryIndex.value ** 2.0

        let epsDiagonal (p : OpticalProperties) =
            let (Eps (ComplexMatrix3x3 (ComplexMatrix e))) = p.eps
            [ e.[0, 0].Real; e.[1, 1].Real; e.[2, 2].Real ]
        let rhoDiagonalImaginary (p : OpticalProperties) =
            let (Rho (ComplexMatrix3x3 (ComplexMatrix r))) = p.rho
            [ r.[0, 0].Imaginary; r.[1, 1].Imaginary; r.[2, 2].Imaginary ]

        // z-cut at zero azimuth: the crystal frame IS the lab frame.
        let zCut = orientForCut ZCut (SampleAzimuth.degree 0.0) props
        let assertClose (label : string) (expected : float list) (actual : float list) =
            List.zip expected actual
            |> List.iteri (fun i (e, a) -> Assert.True(abs (e - a) < 1.0e-9, $"{label}[{i}]: expected {e}, got {a}"))

        assertClose "z-cut eps" [ nOrdSq; nOrdSq; nExtSq ] (epsDiagonal zCut)
        assertClose "z-cut rho" [ quartzG11.value; quartzG11.value; quartzG33.value ] (rhoDiagonalImaginary zCut)

        // x-cut: a 90 deg rotation about y carries the crystal 3-axis onto the lab 1-axis, so the
        // extraordinary component moves from the third diagonal slot to the first — and, critically, the
        // GYRATION tensor moves with it. Rotating eps without rotating rho is precisely the bug that
        // routing both through the engine's own OpticalProperties.rotate makes impossible.
        let xCut = orientForCut XCut (SampleAzimuth.degree 0.0) props
        assertClose "x-cut eps" [ nExtSq; nOrdSq; nOrdSq ] (epsDiagonal xCut)
        assertClose "x-cut rho" [ quartzG33.value; quartzG11.value; quartzG11.value ] (rhoDiagonalImaginary xCut)

    // =================================================================================================
    // T4 — parameter scaling. The guard on the fixed-step differentiation trap.
    // =================================================================================================

    [<Fact>]
    member _.``toScaled and ofScaled round-trip, and a unit scaled step is the intended physical step`` () =
        // Why this fact exists at all: AlglibAdapter.runLm differentiates with a FIXED ABSOLUTE step of
        // 1e-6. Against a gyration component of 1e-4 that is a 1 % perturbation - far outside the linear
        // regime a Jacobian assumes - so the fit must search a dimensionless, O(1) vector and map back to
        // physical units inside the residual. A silent error in that mapping does not fail loudly; it
        // converges smoothly to the wrong answer. Hence: pin it.
        let scaling =
            {
                centre = quartz
                scale =
                    {
                        ordinaryIndex = RefractionIndex 1.0e-3
                        extraordinaryIndex = RefractionIndex 1.0e-3
                        g11 = RhoValue 1.0e-5
                        g33 = RhoValue 1.0e-5
                    }
            }

        // Round trip through the scaled space is exact for the centre itself (the zero vector) ...
        let atCentre = toScaled scaling quartz
        Assert.Equal<float[]>([| 0.0; 0.0; 0.0; 0.0 |], atCentre)

        // ... and for an arbitrary offset.
        let offset : MaterialParameters =
            {
                ordinaryIndex = RefractionIndex (quartzOrdinaryIndex.value + 3.5e-3)
                extraordinaryIndex = RefractionIndex (quartzExtraordinaryIndex.value - 1.25e-3)
                g11 = RhoValue (quartzG11.value + 2.0e-5)
                g33 = RhoValue (quartzG33.value - 4.0e-5)
            }
        let scaled = toScaled scaling offset
        Assert.True(abs (scaled.[0] - 3.5) < 1.0e-9, $"scaled n_o = {scaled.[0]}")
        Assert.True(abs (scaled.[1] + 1.25) < 1.0e-9, $"scaled n_e = {scaled.[1]}")
        Assert.True(abs (scaled.[2] - 2.0) < 1.0e-9, $"scaled g11 = {scaled.[2]}")
        Assert.True(abs (scaled.[3] + 4.0) < 1.0e-9, $"scaled g33 = {scaled.[3]}")

        let back = ofScaled scaling scaled
        Assert.True(abs (back.ordinaryIndex.value - offset.ordinaryIndex.value) < 1.0e-15, "n_o round trip")
        Assert.True(abs (back.extraordinaryIndex.value - offset.extraordinaryIndex.value) < 1.0e-15, "n_e round trip")
        Assert.True(abs (back.g11.value - offset.g11.value) < 1.0e-18, "g11 round trip")
        Assert.True(abs (back.g33.value - offset.g33.value) < 1.0e-18, "g33 round trip")

        // A UNIT step in each scaled coordinate must move exactly that one physical parameter, by exactly
        // its scale. This is the property the optimizer actually relies on: it is what makes a 1e-6 step
        // in the scaled space a 1e-9 step in n and a 1e-11 step in g rather than a 1e-6 step in both.
        let unitStep = ofScaled scaling [| 1.0; 0.0; 0.0; 0.0 |]
        Assert.True(abs (unitStep.ordinaryIndex.value - (quartzOrdinaryIndex.value + 1.0e-3)) < 1.0e-15, "unit step moves n_o by its scale")
        Assert.True(abs (unitStep.extraordinaryIndex.value - quartzExtraordinaryIndex.value) < 1.0e-15, "unit step in n_o leaves n_e alone")
        Assert.True(abs (unitStep.g11.value - quartzG11.value) < 1.0e-18, "unit step in n_o leaves g11 alone")

    // =================================================================================================
    // T3 — the closed-form analytic inversion.
    // =================================================================================================

    [<Fact>]
    member _.``muellerOfBirefringence reproduces the repository's own retarder and rotator primitives`` () =
        // The analytic inversion's sign conventions are pinned against the primitives that already exist,
        // not against a paper. If muellerOfBirefringence and retarderMueller / rotationMueller ever
        // disagree, the inversion is producing coefficients in some other convention and every starting
        // value derived from it is silently wrong.
        let lb = Retardance.degree 37.0
        let zero = Retardance 0.0

        // A pure linear retardance with fast axis at 0 deg IS retarderMueller at azimuth 0.
        assertMuellerEqual (retarderMueller Angle.zero lb) (muellerOfBirefringence lb zero zero)

        // A pure linear retardance with fast axis at 45 deg IS retarderMueller at azimuth 45.
        assertMuellerEqual (retarderMueller (Angle.degree 45.0) lb) (muellerOfBirefringence zero lb zero)

        // A pure circular retardance of cb IS the Stokes frame rotation through cb / 2: an optical rotator
        // turns the polarization azimuth by half its circular retardance.
        let cb = Retardance.degree 50.0
        assertMuellerEqual (Propagation.rotationMueller (Angle (cb.value / 2.0))) (muellerOfBirefringence zero zero cb)

        // Zero everywhere is the identity — the rotation vector vanishes and the Rodrigues short-circuit
        // must not divide by its own zero norm.
        assertMuellerEqual Propagation.identityMueller (muellerOfBirefringence zero zero zero)

    [<Fact>]
    member _.``analyticInversion inverts muellerOfBirefringence exactly and reports zero dichroism`` () =
        // The round trip that makes Stage A trustworthy as a starting-value generator.
        let cases =
            [ "pure linear at 0", Retardance.degree 37.0, Retardance 0.0, Retardance 0.0
              "pure linear at 45", Retardance 0.0, Retardance.degree -22.0, Retardance 0.0
              "pure circular", Retardance 0.0, Retardance 0.0, Retardance.degree 50.0
              "mixed", Retardance.degree 31.0, Retardance.degree 12.0, Retardance.degree -44.0 ]

        for (label, lb, lbPrime, cb) in cases do
            match analyticInversion (muellerOfBirefringence lb lbPrime cb) with
            | Ok a ->
                Assert.True(abs (a.lb.value - lb.value) < 1.0e-12, $"{label}: lb {a.lb.value} vs {lb.value}")
                Assert.True(abs (a.lbPrime.value - lbPrime.value) < 1.0e-12, $"{label}: lbPrime {a.lbPrime.value} vs {lbPrime.value}")
                Assert.True(abs (a.cb.value - cb.value) < 1.0e-12, $"{label}: cb {a.cb.value} vs {cb.value}")
                // A pure birefringence has no dichroism at all, so the transparency residual is exactly the
                // number that tells a caller whether a MEASURED matrix is the transparent, non-depolarizing
                // object the inversion assumes.
                Assert.True(transparencyResidual a < 1.0e-12, $"{label}: transparency residual = {transparencyResidual a}")
            | Error e -> Assert.Fail($"{label}: expected an inversion, got %A{e}")

    [<Fact>]
    member _.``analyticInversion reports the degenerate cases as typed errors rather than plausible numbers`` () =
        // A half-turn leaves the rotation axis genuinely ambiguous in sign, and a block that is not a
        // rotation is not interpretable at all. Both must be typed errors: returning a plausible-looking
        // coefficient for either would corrupt the starting values silently, which is far worse than
        // failing.
        match analyticInversion (muellerOfBirefringence (Retardance.degree 180.0) (Retardance 0.0) (Retardance 0.0)) with
        | Error (DegenerateRotation reason) -> Assert.False(System.String.IsNullOrWhiteSpace reason)
        | other -> Assert.Fail($"expected a DegenerateRotation for a half-turn, got %A{other}")

        // A matrix with non-positive m00 carries no usable intensity to normalize by.
        let dark = Propagation.muellerOfRows [ for _ in 0 .. 3 -> [ for _ in 0 .. 3 -> 0.0 ] ]
        match analyticInversion dark with
        | Error (NonPositiveIntensity m00) -> Assert.Equal(0.0, m00)
        | other -> Assert.Fail($"expected a NonPositiveIntensity for a zero matrix, got %A{other}")

    [<Fact>]
    member _.``cloudeEigenvalues identify a non-depolarizing matrix and the depolarization index agrees`` () =
        // The Cloude coherency matrix is positive semi-definite exactly when a Mueller matrix is
        // physically realizable, and has exactly ONE non-zero eigenvalue when the matrix is
        // non-depolarizing. Both properties are pinned here on matrices whose answer is known a priori, so
        // that the same functions can be trusted as a realizability check on solver output below.
        let nonDepolarizing = muellerOfBirefringence (Retardance.degree 31.0) (Retardance.degree 12.0) (Retardance.degree -44.0)
        match cloudeEigenvalues nonDepolarizing with
        | [ l0; l1; l2; l3 ] ->
            Assert.True(abs (l0 - 1.0) < 1.0e-9, $"dominant Cloude eigenvalue = {l0}")
            for (i, l) in List.indexed [ l1; l2; l3 ] do
                Assert.True(abs l < 1.0e-9, $"Cloude eigenvalue {i + 1} = {l}, expected ~0 for a non-depolarizing matrix")
        | other -> Assert.Fail($"expected four Cloude eigenvalues, got %A{other}")

        match depolarizationIndex nonDepolarizing with
        | Ok di -> Assert.True(abs (di - 1.0) < 1.0e-9, $"depolarization index of a pure retarder = {di}")
        | Error e -> Assert.Fail($"expected a depolarization index, got %A{e}")

        // The ideal depolarizer is the opposite extreme: it survives realizability (all four eigenvalues
        // equal and positive) but has a depolarization index of 0.
        let depolarizer =
            Propagation.muellerOfRows
                [ [ 1.0; 0.0; 0.0; 0.0 ]
                  [ 0.0; 0.0; 0.0; 0.0 ]
                  [ 0.0; 0.0; 0.0; 0.0 ]
                  [ 0.0; 0.0; 0.0; 0.0 ] ]
        Assert.True(cloudeEigenvalues depolarizer |> List.forall (fun l -> l > -1.0e-12), "the ideal depolarizer must stay realizable")
        match depolarizationIndex depolarizer with
        | Ok di -> Assert.True(abs di < 1.0e-12, $"depolarization index of an ideal depolarizer = {di}")
        | Error e -> Assert.Fail($"expected a depolarization index, got %A{e}")

    // =================================================================================================
    // T5 / T6 — the forward model, against an EXTERNAL number and against physics invariants.
    // =================================================================================================

    [<Fact>]
    member _.``C1 is a pure optical rotator whose rotatory power is exactly 2 pi g11 d over lambda`` () =
        // The most valuable fact in this file: an end-to-end check of the whole forward chain - material
        // assembly, the Rho.fromIm sign convention, Berreman propagation, plate multiple reflections and
        // muellerMatrixT() - against a CLOSED FORM, at machine precision.
        //
        // What the engine actually does, established by measuring it (varying g11, g33, n and d
        // independently) rather than assumed:
        //
        //     Delta_n_circular = 2 * rho_transverse      ->   specific rotation = 2 pi g11 / lambda
        //
        // It is driven by the TRANSVERSE Rho component g11, is exactly independent of g33, and is exactly
        // independent of the refractive index. Agreement with the closed form is to 2e-16 relative.
        //
        // A CONVENTION WARNING, and the reason this fact does not assert the literature figure. The
        // engine's Rho is the bi-anisotropic (Tellegen-Post) magnetoelectric tensor of D = eps E + rho H,
        // not the crystallographic gyration tensor g of D = eps E + i (G x E). The two share the symbol g
        // in the literature and in Active.Rho.type_3_4_6_Crystal, but they are different
        // parameterizations. Reading the same quartz constants crystallographically gives
        // pi g33 / (n lambda) = 18.62 deg/mm, which matches the MEASURED rotatory power of alpha-quartz at
        // 632.8 nm (18.8 deg/mm) to within 1 %; reading them as this engine does gives 33.57 deg/mm. To
        // make the engine reproduce 18.8 deg/mm the transverse Rho component would have to be 3.305e-5,
        // not 5.9e-5. Neither number is wrong - they answer different questions - but anyone quoting a
        // gyration value out of this pipeline must know which one they have.
        //
        // If this fact fails, the forward model has changed and every inverse result below is meaningless,
        // which is exactly why it is asserted before anything is fitted.
        let observations = observe c1
        let m = (List.exactlyOne observations).measured

        match analyticInversion m with
        | Ok a ->
            // A pure rotator has no linear birefringence in either basis: along the optic axis the two
            // transverse directions are equivalent, so there is nothing to retard against anything else.
            Assert.True(abs a.lb.degrees < 1.0e-6, $"C1 linear retardance at 0 deg = {a.lb.degrees} deg, expected ~0")
            Assert.True(abs a.lbPrime.degrees < 1.0e-6, $"C1 linear retardance at 45 deg = {a.lbPrime.degrees} deg, expected ~0")

            // The circular retardance is twice the azimuth rotation, so the rotation over the plate is
            // |cb| / 2 degrees.
            // Both lengths carry the engine's `meter` unit, so their ratio is dimensionless by
            // construction — the unit system is doing the bookkeeping rather than a comment.
            let plateMeters =
                match thickPlate with
                | Thickness t -> t
                | Infinity -> failwith "the C1 plate must have a finite thickness"
            let platesPerWave = plateMeters / waveLength.value
            let predictedDeg = 2.0 * System.Math.PI * abs quartzG11.value * platesPerWave / degree
            let rotationDeg = abs a.cb.degrees / 2.0
            let relative = abs (rotationDeg - predictedDeg) / predictedDeg
            // Pinned per the spec §9 protocol from an observed relative deviation of 2.1e-16 — i.e. the
            // engine reproduces the closed form to the last bit a double can carry.
            Assert.True(
                relative < 1.0e-12,
                $"C1 rotation = {rotationDeg} deg; closed form 2*pi*g11*d/lambda = {predictedDeg} deg (relative deviation {relative})")

            // And it is transparent: no dichroism of any kind.
            Assert.True(transparencyResidual a < 1.0e-9, $"C1 transparency residual = {transparencyResidual a}")
        | Error e -> Assert.Fail($"C1 should invert to a pure rotator, got %A{e}")

    [<Fact>]
    member _.``C1 is completely blind to g33, which is why a second crystal cut is required`` () =
        // The physical claim the whole experiment design rests on, asserted directly rather than argued.
        // Propagating along the optic axis, the transverse Rho components are both g11; the crystal
        // 3-axis is parallel to the propagation direction and therefore invisible. Doubling g33 - or
        // flipping its sign - must change NOTHING about the measured matrix.
        //
        // This is the forward-model half of the ablation result; the fit-side half (a vanishing Jacobian
        // column and an unbounded condition number) is asserted below.
        let baseline = observe c1 |> List.exactlyOne
        let c = baseline.configuration

        let withG33 (g : float) =
            match forward.muellerOf c { quartz with g33 = RhoValue g } with
            | Ok m -> m
            | Error e -> failwith $"the forward model failed: %A{e}"

        assertMuellerEqual baseline.measured (withG33 (2.0 * quartzG33.value))
        assertMuellerEqual baseline.measured (withG33 (-quartzG33.value))
        assertMuellerEqual baseline.measured (withG33 0.0)

    [<Fact>]
    member _.``every configuration produces a physically realizable, essentially non-depolarizing Mueller matrix`` () =
        // Two invariants over the whole measurement set.
        //
        // REALIZABILITY is absolute: a negative Cloude eigenvalue would mean the forward model had
        // produced a matrix no real optical element could produce, and no tolerance can excuse that. Only
        // round-off is allowed.
        //
        // NON-DEPOLARIZATION is deliberately NOT asserted strictly, and that is a physics statement rather
        // than a slack tolerance. With numberOfReflections = 3 the plate solver sums the Mueller matrices
        // of the emerging beams INCOHERENTLY, and a sum of Mueller-Jones matrices is in general
        // depolarizing. So the depolarization index is below 1 BY CONSTRUCTION and a test demanding
        // exactly 1 would be asserting something false about the model it is testing.
        //
        // How much depolarization, measured rather than estimated (worst 1 - DI per group):
        //
        //     C1  (z-cut, normal, transmission)   1.1e-16   effectively none
        //     C3  (x-cut, normal, transmission)   2.7e-03
        //     C4  (x-cut, oblique, transmission)  4.2e-03
        //     C2  (z-cut, oblique, transmission)  2.9e-02
        //     C2  (z-cut, oblique, REFLECTION)    9.4e-02
        //     C4  (x-cut, oblique, REFLECTION)    4.2e-01   <- the extreme
        //
        // The pattern is physical and worth understanding, because it is easy to mistake for a defect.
        // TRANSMISSION is dominated by the direct beam: the twice-bounced beam carries only ~0.2 % of it
        // at quartz's 4.55 % surface reflectance, so the sum stays close to a single Mueller-Jones matrix.
        // REFLECTION has no such dominant term - the front-surface reflection (~4.5 %) and the beam that
        // has traversed the plate and reflected internally (~4.1 %) are COMPARABLE in amplitude while
        // undergoing quite different polarization transformations, so summing them genuinely destroys
        // polarization. Hence two bands: a tight one for transmission, where a defect would show, and a
        // loose one for reflection, where 40 % depolarization is the correct answer.
        //
        // A consequence recorded here because it constrains use of this suite: the closed-form analytic
        // inversion assumes a Mueller-Jones matrix, so it is meaningful for the transmission
        // configurations and NOT for the reflection ones. The nonlinear fit is unaffected - it compares
        // against the full Berreman model, which reproduces the depolarization exactly.
        let observations = observe fullConfigurations
        Assert.True(observations.Length > 20, $"the measurement set should be substantial, got {observations.Length}")

        let mutable worstTransmitted = 0.0
        let mutable worstOverall = 0.0
        for o in observations do
            let eigenvalues = cloudeEigenvalues o.measured
            let smallest = List.min eigenvalues
            Assert.True(
                smallest > -1.0e-9,
                $"%A{o.configuration.cut} at {o.configuration.incidenceAngle.value / degree} deg: negative Cloude eigenvalue {smallest} — the matrix is not physically realizable")

            match depolarizationIndex o.measured with
            | Ok di ->
                Assert.True(di <= 1.0 + 1.0e-9, $"depolarization index {di} exceeds 1, which is impossible")
                worstOverall <- max worstOverall (1.0 - di)
                if o.configuration.observable = TransmittedMueller then
                    worstTransmitted <- max worstTransmitted (1.0 - di)
            | Error e -> Assert.Fail($"expected a depolarization index, got %A{e}")

        // Pinned per the spec §9 protocol at ~1.7x and ~1.2x the observed worst values.
        Assert.True(
            worstTransmitted < 0.05,
            $"worst transmission depolarization = {worstTransmitted}; the modelled multiple reflections should contribute a few percent at most")
        Assert.True(
            worstOverall < 0.5,
            $"worst depolarization over the whole set = {worstOverall}; reflection from a thick plate depolarizes strongly, but not without limit")

    // =================================================================================================
    // T10 / T11 — the proxies: mock-driven logic, and typed errors at every boundary.
    // =================================================================================================

    [<Fact>]
    member _.``the residual pipeline runs end to end against mock proxies, with no solver and no optimizer`` () =
        // The guarantee spec 0042 established for its data path, applied to the forward model and the
        // optimizer: every piece of Stage-B logic - scaling, forward evaluation, normalization, residual
        // assembly - must be exercisable with no numerical machinery present at all. If this fact needs a
        // real solver to pass, the logic and the physics are entangled.
        let cannedModel = muellerOfBirefringence (Retardance.degree 20.0) (Retardance 0.0) (Retardance.degree 5.0)
        let cannedMeasurement = muellerOfBirefringence (Retardance.degree 20.0) (Retardance 0.0) (Retardance.degree 5.0)

        let mockForward : ForwardModelProxy =
            { muellerOf = fun _ _ -> Ok cannedModel }

        let mockSolver : NonlinearSolverProxy =
            { solveNonlinearLeastSquares = fun request -> Ok { solution = request.initial; finalResiduals = request.residual request.initial; iterations = 7 } }

        let observations =
            [ for c in c1 -> { configuration = c; measured = cannedMeasurement } ]

        // The forward proxy is driven through its exact declared signature.
        match forwardModels mockForward quartz observations with
        | Ok models ->
            Assert.Equal(observations.Length, models.Length)
            match residualVector observations models with
            | Ok residuals ->
                // 15 residual entries per observation: the normalized elements other than m00, which
                // normalization has forced to 1 in both and which would therefore contribute a residual
                // entry that is identically zero.
                Assert.Equal(15 * observations.Length, residuals.Length)
                // Model and measurement are the same matrix here, so every residual entry is zero.
                Assert.True(residuals |> Array.forall (fun r -> abs r < 1.0e-15), "identical model and measurement must give a zero residual")
            | Error e -> Assert.Fail($"expected a residual vector, got %A{e}")
        | Error e -> Assert.Fail($"expected mock forward models, got %A{e}")

        // The solver proxy is driven through its exact declared signature.
        let request =
            {
                residual = fun v -> Array.map (fun x -> x - 1.0) v
                initial = [| 0.0; 0.0; 0.0; 0.0 |]
                lowerBounds = Array.create 4 -10.0
                upperBounds = Array.create 4 10.0
                maxIterations = 100
                epsX = 1.0e-10
            }
        match mockSolver.solveNonlinearLeastSquares request with
        | Ok solution ->
            Assert.Equal(7, solution.iterations)
            Assert.Equal<float[]>(request.initial, solution.solution)
        | Error e -> Assert.Fail($"expected the canned mock solution, got %A{e}")

    [<Fact>]
    member _.``both proxies compare by reference (the ReferenceEquality convention)`` () =
        // Both records' only fields are function-valued, so they have no structural equality; the
        // attribute makes them compare by identity so a host context holding one stays comparable. Mirrors
        // the ExperimentDataProxy / MuellerSolverProxy / MuellerDataProxy convention.
        let f : ForwardModelProxy = { muellerOf = fun _ _ -> Ok Propagation.identityMueller }
        let g : ForwardModelProxy = { muellerOf = fun _ _ -> Ok Propagation.identityMueller }
        Assert.True((f = f))
        Assert.False((f = g))

        let s : NonlinearSolverProxy = { solveNonlinearLeastSquares = fun _ -> Error (DidNotConverge "mock") }
        let t : NonlinearSolverProxy = { solveNonlinearLeastSquares = fun _ -> Error (DidNotConverge "mock") }
        Assert.True((s = s))
        Assert.False((s = t))

    [<Fact>]
    member _.``every boundary maps failure to a typed error, never a throw`` () =
        // The forward model wraps OpticalSystemSolver, which THROWS on degenerate input (getMuellerMatrix
        // ends in failwith "Invalid combination of parameters..."). That exception must be caught AT the
        // proxy and mapped, so that F# above the boundary never handles exceptions.
        //
        // A zero refractive index is degenerate enough to break the eigen-decomposition while remaining a
        // perfectly ordinary value of the parameter type — exactly the kind of input an optimizer can
        // wander into mid-search, which is why the boundary has to be total rather than merely careful.
        let degenerate : MaterialParameters =
            { quartz with ordinaryIndex = RefractionIndex 0.0; extraordinaryIndex = RefractionIndex 0.0 }

        match forward.muellerOf (List.exactlyOne c1) degenerate with
        | Error (ForwardSolveFailed (_, reason)) -> Assert.False(System.String.IsNullOrWhiteSpace reason)
        | Ok _ -> ()   // If the engine happens to survive it, that is fine — the requirement is "no throw".

        // The residual assembler rejects a model list that does not line up with the observations, rather
        // than silently fitting a truncated problem.
        let observations = [ for c in c1 -> { configuration = c; measured = Propagation.identityMueller } ]
        match residualVector observations [] with
        | Error (MismatchedObservations (measured, model)) ->
            Assert.Equal(observations.Length, measured)
            Assert.Equal(0, model)
        | other -> Assert.Fail($"expected a MismatchedObservations error, got %A{other}")

        // The real ALGLIB-backed solver proxy rejects a malformed request without reaching ALGLIB at all.
        let solver = MuellerInverseSolver.createAlglibLevenbergMarquardt ()
        let malformed =
            {
                residual = fun v -> v
                initial = [| 0.0; 0.0 |]
                lowerBounds = [| 0.0 |]
                upperBounds = [| 1.0; 1.0 |]
                maxIterations = 10
                epsX = 1.0e-9
            }
        match solver.solveNonlinearLeastSquares malformed with
        | Error (InvalidNonlinearRequest reason) -> Assert.False(System.String.IsNullOrWhiteSpace reason)
        | other -> Assert.Fail($"expected an InvalidNonlinearRequest, got %A{other}")

    [<Fact>]
    member _.``the full C1-C4 measurement set recovers every material constant from a perturbed start`` () =
        // The deliverable: from noiseless synthetic data generated by the forward model, recover all four
        // material constants starting from a deliberately wrong guess.
        let (observations, scaling, _, solution) = runFit fullConfigurations perturbedStart
        let recovered = ofScaled scaling solution.solution

        // The fit must actually have moved: a "recovery" that never left the start point would pass a
        // sloppy tolerance while proving nothing.
        Assert.True(solution.iterations > 0, "the fit should have taken at least one step")

        let errors =
            [ "n_o", relativeError recovered.ordinaryIndex.value quartzOrdinaryIndex.value
              "n_e", relativeError recovered.extraordinaryIndex.value quartzExtraordinaryIndex.value
              "g11", relativeError recovered.g11.value quartzG11.value
              "g33", relativeError recovered.g33.value quartzG33.value ]
        let report = System.String.Join("; ", [ for (n, e) in errors -> $"{n} rel err {e}" ])

        // Band pinned per the spec §9 protocol at ~70x the observed worst relative error of 1.4e-13
        // (recorded in the implementation log): with noiseless data generated by the very model being
        // fitted, the optimizer recovers every constant to essentially machine precision, so anything
        // looser would not be measuring the fit at all.
        for (name, err) in errors do
            Assert.True(err < 1.0e-11, $"{name} was not recovered: {report}")

        // The residual at the solution must be essentially zero: the data is noiseless and was generated
        // by the very model being fitted, so anything else means the fit stopped short of the truth.
        let finalChiSquared = solution.finalResiduals |> Array.sumBy (fun r -> r * r)
        Assert.True(finalChiSquared < 1.0e-18, $"final chi-squared = {finalChiSquared}; {report}")

        // And the recovered parameters must REPRODUCE THE MEASUREMENTS, not merely sit near the truth.
        match forwardModels forward recovered observations with
        | Ok models ->
            match residualVector observations models with
            | Ok r ->
                let worst = r |> Array.map abs |> Array.max
                Assert.True(worst < 1.0e-9, $"worst normalized Mueller element residual at the solution = {worst}")
            | Error e -> Assert.Fail($"expected a residual vector, got %A{e}")
        | Error e -> Assert.Fail($"expected forward models at the solution, got %A{e}")

        // Guard against a vacuous pass: the start point must NOT already satisfy the acceptance band.
        let startErrors =
            [ relativeError perturbedStart.ordinaryIndex.value quartzOrdinaryIndex.value
              relativeError perturbedStart.g11.value quartzG11.value ]
        Assert.True(List.max startErrors > 1.0e-3, "the start guess must be outside the acceptance band, or this fact proves nothing")

    [<Fact>]
    member _.``the full measurement set is well conditioned and every parameter is observable`` () =
        // Identifiability, asserted through the two quantities that survive noiseless data.
        //
        // This matters because the obvious diagnostics DO NOT survive. FitQuality computes
        // Cov = reducedChiSquared * (J^T J)^-1, and on noiseless synthetic data the reduced chi-squared is
        // ~1e-30, so the standard errors and confidence intervals it reports collapse toward zero and say
        // nothing about identifiability. Asserting that the truth lies inside a 95 % interval of width
        // ~1e-15 would be a test that passes for the wrong reason.
        //
        // What DOES survive is anything depending on J alone: the column norms (how much the residual
        // moves when one parameter moves) and the condition number (the ratio of the most- to the
        // least-constrained direction in parameter space). The correlation matrix survives too, because
        // the reduced-chi-squared factor cancels in corr = cov / (sigma_i sigma_j).
        //
        // No fit is run here. Identifiability is a property of the Jacobian at the solution, and for
        // noiseless synthetic data the solution IS the ground truth - so the Jacobian is evaluated there
        // directly. That makes this fact a statement about the EXPERIMENT DESIGN rather than about whether
        // a particular optimizer run converged, and it keeps it cheap.
        //
        // A trap worth recording: FitQuality.residualJacobian steps each parameter by
        // sqrt(eps) * max(|x_p|, 1e-12), which is RELATIVE and therefore collapses to ~1e-20 at exactly
        // x = 0. The Jacobian must not be evaluated at the origin of the scaled space; centring the
        // scaling on the perturbed start puts the truth at a non-zero scaled point.
        let observations = observe fullConfigurations
        let scaling = scalingAround perturbedStart
        let residual = residualFor observations scaling
        let truthPoint = toScaled scaling quartz
        Assert.True(truthPoint |> Array.forall (fun x -> abs x > 1.0e-6), "the Jacobian must not be evaluated at the origin of the scaled space")

        let jacobian = FitQuality.residualJacobian residual truthPoint
        let norms = jacobianColumnNorms jacobian
        let condition = jacobianCondition jacobian
        let report = System.String.Join("; ", [ for i in 0 .. 3 -> $"{parameterNames.[i]} |J| = {norms.[i]}" ])

        // Every parameter must actually move the residual - this is what "observable" means, and it is the
        // property the ablation fact below shows can fail.
        for i in 0 .. 3 do
            Assert.True(norms.[i] > 1.0e-6, $"{parameterNames.[i]} is unobservable in the full measurement set: {report}")

        // Bands pinned per §9 from the observed values, recorded in the implementation log.
        Assert.True(System.Double.IsFinite condition, $"the Jacobian condition number must be finite, got {condition}")
        Assert.True(condition < 5.0e3, $"Jacobian condition number = {condition}; {report}")

        // The correlation matrix is scale-free and therefore meaningful even at zero residual.
        //
        // MEASURED RESULT, and a genuine property of this experiment design rather than a slack tolerance:
        // n_o and n_e are correlated at 0.99999. That is physical. Linear retardance depends on the
        // DIFFERENCE n_e - n_o through 2 pi (n_e - n_o) d / lambda, and that difference is 0.009 against
        // absolute indices of 1.54 - so the data constrains the difference about 170 times better than it
        // constrains the common level, and moving both indices together is very nearly a null direction.
        // The fit still resolves both (the round-trip fact recovers each to better than 1e-3 relative),
        // because "very nearly" is not "exactly": the Fresnel amplitudes and the internal refraction angle
        // do depend on the absolute level, which is precisely what the oblique-incidence and reflection
        // configurations contribute.
        //
        // The band is therefore pinned just above the observed 0.99999 for the index pair, and much
        // tighter for every other pair, so that a genuine degeneracy - an experiment set that lost the
        // absolute-index information altogether - would still fail this fact.
        // The correlation is computed from the JACOBIAN, not from FitQuality.reportFrom. FitQuality
        // derives it from Cov = reducedChiSquared * (J^T J)^-1, and although the reducedChiSquared factor
        // cancels in the ratio ALGEBRAICALLY, it does not cancel in floating point: here the reduced
        // chi-squared is ~1e-30, the covariance diagonal underflows, and the report's zero-guard returns a
        // flat 0.0 for every off-diagonal - a value indistinguishable from "perfectly independent" and so
        // actively misleading. This was measured, not assumed. FitQuality is still the right tool once
        // real noise is present; jacobianCorrelation is the diagnostic for the noiseless case.
        let correlation = jacobianCorrelation jacobian
        let pairs =
            [ for i in 0 .. 3 do
                for j in i + 1 .. 3 ->
                    $"{parameterNames.[i]}/{parameterNames.[j]}", abs correlation.[i].[j] ]
        let pairReport = System.String.Join("; ", [ for (n, c) in pairs -> $"{n} = {c}" ])
        for (name, corr) in pairs do
            let bound = if name = "n_o/n_e" then 0.999999 else 0.5
            Assert.True(corr < bound, $"parameter correlation {name} = {corr} exceeds {bound}; all pairs: {pairReport}")

    [<Fact>]
    member _.``C1 alone cannot determine three of the four constants, which is why the design needs more cuts`` () =
        // The ablation, and the executable answer to "what experiments are needed". Asserting the FAILURE
        // is what turns the multi-configuration design from an assumption into a result.
        //
        // Propagating along the optic axis at normal incidence, the wave sees only the transverse Rho
        // components (both g11) and the ordinary index; the crystal 3-axis is parallel to the propagation
        // direction, so neither n_e nor g33 has ANY effect at all - their Jacobian columns are identically
        // zero, not merely small.
        //
        // n_o is the interesting case, and the measured answer is subtler than "it divides out". The
        // normalized matrix does still depend on it, but only through a second-order channel: the plate
        // emits a direct beam rotated by psi and a twice-bounced beam rotated by 3 psi, and n_o sets the
        // RELATIVE WEIGHT of the two through the surface reflectance. Because 2x2 rotations commute and
        // form a one-parameter group, that weighted sum is itself exactly a scaled rotation - which is why
        // C1 shows no depolarization at all (measured index of departure 1.1e-16) even though two beams
        // are being summed - but its ANGLE shifts slightly with the weight, and hence with n_o. The
        // measured sensitivity is real, not numerical noise: it is about three orders of magnitude below
        // g11's and about three orders above the forward model's numerical floor.
        //
        // So C1 leaves two parameters structurally invisible and a third constrained ~700 times more
        // weakly than the one it actually measures. That is what "one configuration is not enough" means
        // quantitatively.
        // The Jacobian is evaluated at the TRUTH, expressed in a scaling centred on the perturbed start so
        // that no coordinate is exactly zero. That detail is load-bearing: FitQuality.residualJacobian
        // steps each parameter by sqrt(eps) * max(|x_p|, 1e-12), which collapses to ~1e-20 at x = 0 and
        // would report EVERY column as dead — including the one that is genuinely alive, turning this fact
        // into a false positive.
        let scaling = scalingAround perturbedStart
        let truthPoint = toScaled scaling quartz
        let residual = residualFor (observe c1) scaling
        let jacobian = FitQuality.residualJacobian residual truthPoint
        let norms = jacobianColumnNorms jacobian
        let report = System.String.Join("; ", [ for i in 0 .. 3 -> $"{parameterNames.[i]} |J| = {norms.[i]}" ])

        // g11 is what C1 measures, and it must be strongly constrained.
        Assert.True(norms.[2] > 1.0e-3, $"g11 must be observable from C1: {report}")

        // n_e and g33 are STRUCTURALLY invisible - exactly zero, not merely small.
        for i in [ 1; 3 ] do
            Assert.True(norms.[i] = 0.0, $"{parameterNames.[i]} must be exactly UNOBSERVABLE from C1 alone: {report}")

        // n_o survives only through the multiple-reflection channel described above, at roughly a
        // thousandth of g11's sensitivity. Both halves of that are asserted: it is not zero (so the
        // channel is real), and it is negligible against g11 (so C1 does not usefully determine it).
        Assert.True(norms.[0] > 0.0, $"n_o should retain a weak multiple-reflection sensitivity: {report}")
        Assert.True(
            norms.[0] < norms.[2] / 100.0,
            $"n_o must be far more weakly constrained than g11 from C1 alone: {report}")

        // With two dead directions the problem is singular, not merely ill conditioned.
        let condition = jacobianCondition jacobian
        Assert.True(
            condition > 1.0e12,
            $"C1 alone must be singular, got condition number {condition}; {report}")

        // Adding C3 - the second crystal cut - restores the other three, which is precisely the design
        // claim: it is the CUT that buys observability, not more angles on the same sample.
        let restoredResidual = residualFor (observe (c1 @ c3)) scaling
        let restoredNorms = jacobianColumnNorms (FitQuality.residualJacobian restoredResidual truthPoint)
        let restoredReport = System.String.Join("; ", [ for i in 0 .. 3 -> $"{parameterNames.[i]} |J| = {restoredNorms.[i]}" ])
        for i in 0 .. 3 do
            Assert.True(restoredNorms.[i] > 1.0e-6, $"adding the second cut must make {parameterNames.[i]} observable: {restoredReport}")
