language: csharp

env:
  - HOME=/home/travis APPDATA=/home/travis LocalAppData=/home/travis

sudo: required #false
dist: trusty
dotnet: 2.1.105
mono:
- latest
os:
- linux

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-hostfxr-1.0.1
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2

branches:
  except:
    - gh-pages

script:
  - ./build.sh Test quick
