image: Visual Studio 2017
init:
   - git config --global core.autocrlf true
install:
   # Download .NET Core SDK 2.1.105 and add to PATH
   - ps: $urlCurrent = "https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.105/dotnet-sdk-2.1.105-win-x64.zip"
   - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
   - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
   - ps: $tempFileCurrent = [System.IO.Path]::GetTempFileName()
   - ps: (New-Object System.Net.WebClient).DownloadFile($urlCurrent, $tempFileCurrent)
   - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFileCurrent, $env:DOTNET_INSTALL_DIR)
   - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
build_script:
   - build.cmd Test quick
test: off
deploy: off
shallow_clone: true
clone_depth: 1
